airlines/urls.py
from django.urls import path
from .views import search, AirlineDetailView, AddOrderView,SubmitOrderView,ChooseSeatView, CheckBagView, CarbonOffsetView,SurveyView



urlpatterns = [
    path('', AddOrderView.as_view(), name='new_order'),
    path('search/<int:pk>', search, name='search'),
    path('arline_detail/<int:aid>/<int:oid>', AirlineDetailView, name='arline_details'),
    path('submit_order/<int:aid>/<int:oid>', SubmitOrderView.as_view(), name = 'submit_order'),
    path('choose_seat/<int:aid>/<int:oid>', ChooseSeatView.as_view(), name = 'choose_seat'),
    path('check_bag/<int:aid>/<int:oid>', CheckBagView.as_view(), name = 'check_bag'),
    path('carbon_offset/<int:aid>/<int:oid>', CarbonOffsetView.as_view(), name = 'carbon_offset'),
    path('survey/<int:pk>', SurveyView.as_view(), name = 'survey'),
]

filterpackage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('airlines.urls')),
]

airlines/models.py
from email.policy import default
from django.db import models
from django.urls import reverse

class Order(models.Model):
    starting_airport = models.CharField(max_length=100, default='-')
    destination_airport = models.CharField(max_length=100, default='-')
    #airlines = models.CharField(max_length=100, choices=AIRLINE_CHOICES)
    airlines = models.CharField(max_length=100, default='-')
    flight = models.CharField(max_length=100, default='-')
    aircraft_type = models.CharField(max_length=100, default='-')
    departure_time = models.CharField(blank=True, null=True,max_length=10)
    arrival_time = models.CharField(blank=True, null=True,max_length=10)
    punctuality_rate = models.CharField(max_length=100,default='-')
    seat_number = models.CharField(max_length=100,default='-')
    check_bag = models.CharField(max_length=100,default='-')
    price = models.CharField(max_length=10,default='-')
    total_price = models.CharField(max_length=10,default='-')
    carbon_choice = models.CharField(max_length=10,default='-')
    
    subject_gender = models.CharField(max_length=10,default='-')
    subject_age = models.CharField(max_length=10,default='-')
    subject_marital = models.CharField(max_length=10,default='-')

    survery_Q1_a = models.CharField(max_length=30,default='-')
    survery_Q1_b = models.CharField(max_length=30,default='-')
    survery_Q1_c = models.CharField(max_length=30,default='-')
    survery_Q1_d = models.CharField(max_length=30,default='-')
    survery_Q1_e = models.CharField(max_length=30,default='-')

    survery_Q2 = models.CharField(max_length=30,default='-')
    
    survery_Q3_a = models.CharField(max_length=30,default='-')
    survery_Q3_b = models.CharField(max_length=30,default='-')
    survery_Q3_c = models.CharField(max_length=30,default='-')
    survery_Q3_d = models.CharField(max_length=30,default='-')
    
    survery_Q4_a = models.CharField(max_length=30,blank=True)
    survery_Q4_b = models.CharField(max_length=30,blank=True)
    survery_Q4_c = models.CharField(max_length=30,blank=True)
    survery_Q4_d = models.CharField(max_length=30,blank=True)
    survery_Q4_e = models.CharField(max_length=30,blank=True)

    survery_Q5_a = models.CharField(max_length=30,blank=True)
    survery_Q5_b = models.CharField(max_length=30,blank=True)
    survery_Q5_c = models.CharField(max_length=30,blank=True)
    survery_Q5_d = models.CharField(max_length=30,blank=True)
    survery_Q5_e = models.CharField(max_length=30,blank=True)
    survery_Q5_f = models.CharField(max_length=30,blank=True)
    survery_Q5_g = models.CharField(max_length=30,blank=True)
    
    survery_Q6 = models.CharField(max_length=30,default='-',blank=True)
    
    def get_absolute_url(self):
    # set success url
        return reverse("search", kwargs={'pk': self.pk})


class Airline(models.Model):

    AIRLINE_CHOICES = (
            ("金鹏航空","金鹏航空"),
            ("中国国航","中国国航"),
            ("昆明航空","昆明航空"),
            ("深圳航空","深圳航空"),
            ("海南航空","海南航空"),
            ("南方航空","南方航空"),
            ("厦门航空","厦门航空"),
            ("祥鹏航空","祥鹏航空"),
            ("东方航空","东方航空"),
            ("多彩航空","多彩航空"),
            ("天津航空","天津航空"),
            ("华夏航空","华夏航空"),
            ("山东航空","山东航空"),
            ("长龙航空","长龙航空"),
            ("中国联航","中国联航"),
            ("河北航空","河北航空"),
            ("首都航空","首都航空"),
            ("四川航空","四川航空"),
            ("西藏航空","西藏航空"),
            ("成都航空","成都航空"),
            ("吉祥航空","吉祥航空"),
            ("上海航空","上海航空"),
            ("东海航空","东海航空"),
            ("重庆航空","重庆航空"),
            ("西部航空","西部航空"),
            ("幸福航空","幸福航空"),
            ("福州航空","福州航空"),
            ("瑞丽航空","瑞丽航空"),
            ("桂林航空","桂林航空"),
            ("青岛航空","青岛航空"),
            ("北部湾航空","北部湾航空"),
            ("长安航空","长安航空"),
            ("江西航空","江西航空"),
            ("乌鲁木齐航空","乌鲁木齐航空"),
        
    )
    airline_id = models.IntegerField(default=0)
    starting_airport = models.CharField(max_length=100)
    destination_airport = models.CharField(max_length=100)
    #airlines = models.CharField(max_length=100, choices=AIRLINE_CHOICES)
    airlines = models.CharField(max_length=100)
    flight = models.CharField(max_length=100)
    aircraft_type = models.CharField(max_length=100, default='-')
    departure_time = models.TimeField()
    arrival_time = models.TimeField()
    punctuality_rate = models.CharField(max_length=100,default='-')
    price = models.CharField(max_length=10,default='-')

    def get_absolute_url(self):
    #return reverse("article_detail", args=(str(self.pk)))
    #return reverse('home')
        return reverse("arline_detail", kwargs={'pk': self.pk})
    
    

airlines/views.py
from django.shortcuts import render, get_object_or_404
from .models import Airline, Order
from .filters import AirlineFilter
from django.views.generic import DetailView, CreateView, UpdateView, View
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse

import random
from .forms import ChooseSeatForm, CheckBagForm, AddOrderForm, SubmitOrderForm, SurveyForm


def search(request, pk):
    airlines = Airline.objects.none()
    airlineFilter = AirlineFilter(queryset=airlines)

    if request.method == "POST":
        airlineFilter = AirlineFilter(request.POST, queryset=Airline.objects.all())

    context = {
        'airlineFilter': airlineFilter,
        'order_id': pk
    }

    return render(request, 'airlines/search.html', context)

def AirlineDetailView(request, aid, oid):
    print(aid)
    print(oid)
    airline = get_object_or_404(Airline, id=aid)

    current_order =get_object_or_404(Order, id=oid)
    carbon_offset_choice = current_order.carbon_choice
    print(carbon_offset_choice)

    context = {
        "airline":airline,
        "carbon_offset_choice":int(carbon_offset_choice),
        "current_order":current_order.pk,
        "carbon_offset_fee":50,
        "choice_0":0,
        "choice_1":1,
        "choice_2":2,
        "choice_3":3
        

    }
    return render(request, 'airlines/airline_detail.html', context)

# class AirlineDetailView(DetailView):
#     model = Airline
#     template_name = 'airlines/airline_detail.html'

#     def get_context_data(self, *args, **kwargs):
#         #cat_menu = Category.objects.all()
#         context = super(AirlineDetailView, self).get_context_data(
#             *args, **kwargs)
#         print(self)

        
#         current_order = Order.objects.last()
#         carbon_offset_choice = current_order.carbon_choice
#         print(carbon_offset_choice)


#         # context data
#         context['carbon_offset_choice'] = int(carbon_offset_choice)
#         context['choice_0'] = 0
#         context['choice_1'] = 1
#         context['choice_2'] = 2
#         context['choice_3'] = 3
#         context['carbon_offset_fee'] = 50
#         context['current_order'] = current_order.pk
#         # context['post'] = current_post
#         return context

class AddOrderView(CreateView):
    model = Order
    template_name = 'airlines/new_order.html'
    form_class = AddOrderForm
 

class SubmitOrderView(UpdateView):
    model = Order
    template_name = 'airlines/comfirm_order.html'
    # fields = '__all__'
    form_class = SubmitOrderForm
    pk_url_kwarg = 'oid'
    
    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs['oid'])

    def get_success_url(self):
        current_order = Order.objects.get(id=self.kwargs["oid"])
        return reverse_lazy("survey", kwargs={'pk': current_order.pk})

    def get_context_data(self, *args, **kwargs):
        #cat_menu = Category.objects.all()
        context = super(SubmitOrderView, self).get_context_data(
            *args, **kwargs)
        current_order = Order.objects.get(id=self.kwargs["oid"])
        carbon_offset_choice = current_order.carbon_choice

        # context data
        context['current_order'] = current_order.pk
        context['carbon_offset_choice'] = int(carbon_offset_choice)
        context['carbon_offset_fee'] = 50
        context['airline_id'] = self.kwargs["aid"]
        # context['post'] = current_post
        return context  

class ChooseSeatView(UpdateView):
    model = Order
    template_name = 'airlines/choose_seat.html'
    form_class = ChooseSeatForm
    pk_url_kwarg = 'oid'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs['oid'])
    
    def get_success_url(self):
        current_order = Order.objects.get(id=self.kwargs["oid"])
        return reverse_lazy("check_bag", kwargs={'oid': current_order.pk, 'aid':self.kwargs["aid"]})
    
    def get_context_data(self, *args, **kwargs):
        #cat_menu = Category.objects.all()
        context = super(ChooseSeatView, self).get_context_data(
            *args, **kwargs)
        current_order = Order.objects.get(id=self.kwargs["oid"])
        
        # context data
        context['current_order'] = current_order.pk
        context['airline_id'] = self.kwargs["aid"]

        
        # context['post'] = current_post
        return context  
    
class CheckBagView(UpdateView):
    model = Order
    template_name = 'airlines/check_bag.html'
    form_class = CheckBagForm
    pk_url_kwarg = 'oid'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs['oid'])

    def get_success_url(self):
        current_order = Order.objects.get(id=self.kwargs["oid"])
        carbon_offset_choice = int(current_order.carbon_choice)
        return_page = "carbon_offset"
        if carbon_offset_choice == 0 or carbon_offset_choice == 3: # control group &  compulsory fee group
            return_page = "submit_order"
        print(return_page)

        return reverse_lazy(return_page, kwargs={'oid': current_order.pk, 'aid':self.kwargs["aid"]})


    def get_context_data(self, *args, **kwargs):
        #cat_menu = Category.objects.all()
        context = super(CheckBagView, self).get_context_data(
            *args, **kwargs)
        current_order = Order.objects.get(id=self.kwargs["oid"])
        carbon_offset_choice = current_order.carbon_choice
        # context data
        context['carbon_offset_choice'] = int(carbon_offset_choice)
        context['current_order'] = current_order.pk
        context['carbon_offset_fee'] = 50
        context['airline_id'] = self.kwargs["aid"]
        # context['post'] = current_post
        return context     


class CarbonOffsetView(UpdateView):
    model = Order
    template_name = 'airlines/carbon_offset.html'
    fields = ()
    pk_url_kwarg = 'oid'

    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs['oid'])


    def get_success_url(self):
        current_order = Order.objects.get(id=self.kwargs["oid"])
        return reverse_lazy("submit_order", kwargs={'oid': current_order.pk, 'aid':self.kwargs["aid"]})

    def get_context_data(self, *args, **kwargs):
        #cat_menu = Category.objects.all()
        context = super(CarbonOffsetView, self).get_context_data(
            *args, **kwargs) 
        current_order = Order.objects.get(id=self.kwargs["oid"])
        carbon_offset_choice = current_order.carbon_choice

        # context data
        context['carbon_offset_choice'] = int(carbon_offset_choice)
        context['choice_0'] = 0
        context['choice_1'] = 1
        context['choice_2'] = 2
        context['choice_3'] = 3
        context['carbon_offset_fee'] = 50
        context['current_order'] = current_order.pk
        context['airline_id'] = self.kwargs["aid"]
        # context['post'] = current_post
        return context                

class SurveyView(UpdateView):
    model = Order
    template_name = 'airlines/survey.html'
    form_class = SurveyForm
    success_url = reverse_lazy('new_order')

airlines/templates/airlines/airline_detail.html
{% extends 'base.html' %}


{% block title %}
<h1>Airline Detail</h1>
{% endblock  %}
{% block content %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <th>Starting Airport</th>
            <th>Destination Airport</th>
            <th>Airlines</th>
            <th>Flight</th>
            <th>Aircraft Type</th>
            <th>Departure Time</th>
            <th>Arrival Time</th>
            <th>Punctuality Rate</th>
            <th>Ticket Price</th>
        </thead>
        <tbody>
            <tr>
                <td>{{ airline.starting_airport }}</td>
                <td>{{ airline.destination_airport }}</td>
                <td>{{ airline.airlines }}</td>
                <td>{{ airline.flight }}</td>
                <td>{{ airline.aircraft_type }}</td>
                <td>{{ airline.departure_time }}</td>
                <td>{{ airline.arrival_time }}</td>
                <td>{{ airline.punctuality_rate }}</td>
                <td>{{ airline.price }}</td>
            </tr>
        </tbody>
    </table>
</div>
<br>

<center>
<div class="btn-group" >
    <a href="{% url 'search' current_order %}" class="btn btn-secondary">Back</a>
    <a href="{% url 'choose_seat' airline.id current_order %}" class="btn btn-primary" onclick="save_airline()">Next</a>
</div>
</center>

<!-- Passing Data -->
<script>
    localStorage.clear();
    function save_airline(){
        var carbon_choice = "{{ carbon_offset_choice }}";
        

        localStorage.setItem('starting_airport', '{{ airline.starting_airport }}');
        localStorage.setItem('destination_airport', '{{ airline.destination_airport }}');
        localStorage.setItem('airlines', '{{ airline.airlines }}');
        localStorage.setItem('flight', '{{ airline.flight }}');
        localStorage.setItem('aircraft_type', '{{ airline.aircraft_type }}');
        localStorage.setItem('departure_time', '{{ airline.departure_time }}');
        localStorage.setItem('arrival_time', '{{ airline.arrival_time }}');
        localStorage.setItem('punctuality_rate', '{{ airline.punctuality_rate }}');
        localStorage.setItem('price', '{{ airline.price }}');
        localStorage.setItem('carbon_choice', '{{ carbon_offset_choice }}');

        console.log('total price: ' + localStorage.getItem('total_price'));
    }


</script>
{% endblock  %}

airlines/templates/airlines/carbon_offset.html
{% extends 'base.html' %}


{% block title %}

<h1>Carbon Offset</h1>
{% endblock  %}
{% block content %}

<!-- {% if carbon_offset_choice == 0 %}
<div class="card">
<h5 class="card-header">Carbon Offset</h5>
<div class="card-body">
    <h5 class="card-title">Control Group</h5>
    <p class="card-text">Standard procedure; no carbon offset program offered during booking as per usual procedure in most airlines.</p>
    <a href="#" class="btn btn-primary">Go</a>
</div>
</div>
{% endif %} -->

{% if carbon_offset_choice == 1 %}
<div class="card">
    <h5 class="card-header">Carbon Offset</h5>
    <div class="card-body">
        <!-- <h5 class="card-title">Basic Program (Opt-in)</h5> -->
        <!-- <p class="card-text">Carbon offset is offered as a possibility that passengers may choose (opt-in); the few airlines that offer carbon offset during the online booking present it this way.</p> -->
        I accept to pay CNY{{carbon_offset_fee}} to help reduce the
        <a href="#" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Carbon offsetting is simply a way for individuals as airline passengers to “neutralize” their proportion of an aircraft's carbon emissions on a particular journey by investing in carbon reduction projects. This investment includes projects, such as renewable energy from windfarms and hydro-plants."> effects of carbon emmissions (click for more information).</a>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check_button" onclick="switch_check(this)">
            <label class="form-check-label" for="flexCheckDefault">
            Yes
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check_button_no" onclick="switch_check(this)">
            <label class="form-check-label" for="flexCheckChecked">
            No
            </label>
          </div>
    </div>
</div>
{% endif %}

{% if carbon_offset_choice == 2 %}
<div class="card">
    <h5 class="card-header">Carbon Offset</h5>
    <div class="card-body">
        <!-- <h5 class="card-title">Default with Opt-out Choice</h5>
        <p class="card-text">Carbon offset is offered already pre-selected; passengers may refuse this selection (opt-out). This will be one of the innovative defaults tested in this project.</p> -->
        I accept to pay CNY{{carbon_offset_fee}} to help reduce the
        <a href="#" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Carbon offsetting is simply a way for individuals as airline passengers to “neutralize” their proportion of an aircraft's carbon emissions on a particular journey by investing in carbon reduction projects. This investment includes projects, such as renewable energy from windfarms and hydro-plants."> effects of carbon emmissions (click for more information).</a>
        
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check_button" checked onclick="switch_check(this)">
            <label class="form-check-label" for="flexCheckDefault">
            Yes (This option has been selected but you can choose to opt-out.)
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="check_button_no" onclick="switch_check(this)">
            <label class="form-check-label" for="flexCheckChecked">
            No
            </label>
          </div>
        
    </div>
</div>
{% endif %}

<!-- {% if carbon_offset_choice == 3 %}
<div class="card">
    <h5 class="card-header">Carbon Offset</h5>
    <div class="card-body">
        <h5 class="card-title">Default Added Fee (No Opt-out)</h5>
        <p class="card-text">Carbon offset included by default in the ticket cost; The carbon fee will be automatically added to all other aviation taxes and fees. This is the second innovative deafult option being tested in this project.</p>

        <a href="#" class="btn btn-primary">Go</a>
    </div>
</div>
{% endif %} -->
<br /><br />

<center>
    <div class="btn-group" >
        <a href="{% url 'check_bag' airline_id current_order %}" class="btn btn-secondary">Back</a>
        <a href="{% url 'submit_order' airline_id current_order %}" class="btn btn-info" type="button" onclick="check_out()">Checkout</a>
    </div>
</center>


<!-- Passing Data -->
<script>
    function switch_check(obj){
        console.log(document.getElementById(obj.id).checked)
        if(document.getElementById(obj.id).checked){
            // document.getElementById(obj.id).removeAttribute("checked");
            if(obj.id == 'check_button'){
                document.getElementById('check_button_no').checked = false;
            }
            else{
                document.getElementById('check_button').checked = false;
            }
        }
        else{
            if(obj.id == 'check_button'){
                document.getElementById('check_button_no').checked = false;
                
            }
            else{
                document.getElementById('check_button').checked = false;
            }
        }
    }

    function check_out(){
        var carbon_choice = "{{ carbon_offset_choice }}";
        var airline_price = localStorage.getItem("price");
        var check_bag_price = Number(localStorage.getItem('check_bag_price'));
        
        if(carbon_choice == 1 || carbon_choice == 2){
            console.log(document.getElementById('check_button').checked);
            if(document.getElementById('check_button').checked){
                console.log(airline_price + " add {{carbon_offset_fee}} :");
                var fee = Number(airline_price.replace('CNY',""))+Number('{{carbon_offset_fee}}')+check_bag_price;
                console.log(fee);
                localStorage.setItem('total_price', String(fee) + 'CNY');
                localStorage.setItem('paid', "true");
            }
            else {
                console.log("Cancle Fee");
                var fee = Number(airline_price.replace('CNY',""))+check_bag_price;
                localStorage.setItem('total_price', String(fee) + 'CNY'); 
                localStorage.setItem('paid', "false");
            }
        }
        // else if(carbon_choice == 3){
        //     console.log("Default include {{carbon_offset_fee}}");
        //     console.log(airline_price + "add {{carbon_offset_fee}} :");
        //     var fee = Number(airline_price.replace('$',"").split(" ").join(""))+Number('{{carbon_offset_fee}}');
        //     console.log(fee);
        //     localStorage.setItem('total_price', '$'+ String(fee));
        // }
        // else {
        //     console.log('No offset');
        //     localStorage.setItem('total_price', airline_price);
        // }


        console.log('total price: ' + localStorage.getItem('total_price'));
    }


</script>
<script>

    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl)
    })
    
</script>
{% endblock  %}

airlines/templates/airlines/check_bag.html
{% extends 'base.html' %}

{% block title %}
<h1>Check Bag</h1>
{% endblock  %}

{% block content %}

<div class="mb-3">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <br>

        {% if carbon_offset_choice == 0 or carbon_offset_choice == 3 %}
        <center>
            <div class="btn-group" >
                <a href="{% url 'choose_seat' airline_id current_order %}" class="btn btn-secondary">Back</a>
                <button class="btn btn-primary" onclick="save_total()">Order Summary</button>
            </div>
        </center>
        {% else %}
        <center>
            <div class="btn-group" >
                <a href="{% url 'choose_seat' airline_id current_order %}" class="btn btn-secondary">Back</a>
                <button class="btn btn-primary" onclick="save_check_bag()">Next</button>
            </div>
        </center>        
        {% endif %}
    </form>

</div>

<script>
    function save_check_bag(){

        localStorage.setItem('check_bag_price', $("#id_check_bag option:selected").val().split("+")[1].replace('CNY)',""));
        
    }
    function save_total(){

        
        var carbon_choice = "{{ carbon_offset_choice }}";
        var airline_price = localStorage.getItem("price");
        var check_bag_price = Number($("#id_check_bag option:selected").val().split("+")[1].replace('CNY)',""));
        localStorage.setItem('check_bag_price', check_bag_price);


        if(carbon_choice == 3){
            console.log("Default include {{carbon_offset_fee}}");
            console.log(airline_price + "add {{carbon_offset_fee}} :");
            var fee = Number(airline_price.replace('CNY',""))+Number('{{carbon_offset_fee}}')+check_bag_price;
            console.log(fee);
            localStorage.setItem('total_price', String(fee) + 'CNY');  
            localStorage.setItem('paid', "true");          
        }
        else {
            console.log('No offset');
            var fee = Number(airline_price.replace('CNY',""))+check_bag_price;
            localStorage.setItem('total_price', String(fee) + 'CNY'); 
            localStorage.setItem('paid', "false");
        }
        
    }
</script>

{% endblock  %}

airlines/templates/airlines/choose_seat.html
{% extends 'base.html' %}

{% block title %}
<h1>Choose Seat</h1>
{% endblock  %}

{% block content %}

<div class="mb-3">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <br>
        <center>
            <div class="btn-group" >
                <a href="{% url 'arline_details' airline_id current_order %}" class="btn btn-secondary">Back</a>
                <button class="btn btn-primary" type="submit">Next</button>
            </div>
        </center>

    </form>

</div>

{% endblock  %}

airlines/templates/airlines/new_order.html
{% extends 'base.html' %}


{% block title %}
<h1>New Order</h1>
{% endblock  %}
{% block content %}

<br /><br />
<div class="mb-3">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <br>
        <button class="btn btn-success">New Order</button>
    </form>

</div>

{% endblock  %}

airlines/templates/airlines/search.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    Starting Airport: {{ airlineFilter.form.starting_airport }}
    Destination Airport: {{ airlineFilter.form.destination_airport }}
    Airlines: {{ airlineFilter.form.airlines }}
    <br>
    <center>
        <div class="btn-group" >
            <input type="submit" class="btn btn-primary" value="Search"/>
            <a onclick="javascript:location.reload();" class="btn btn-info">Reset</a>
        </div>
    </center>
</form>
<br />
{% if airlineFilter.qs %}
<div class="table-responsive">
    <table class="table table-hover">
        <thead>            
            <th>Starting Airport</th>
            <th>Destination Airport</th>
            <th>Airlines</th>
            <th>Flight</th>
            <th>Aircraft Type</th>
            <th>Departure Time</th>
            <th>Arrival Time</th>
            <th>Punctuality Rate</th>
            <th>Ticket Price</th>
        </thead>
        <tbody>
            {% for airline in airlineFilter.qs %}
            
            <tr class="clickable text-center" onclick="window.location='{% url 'arline_details' airline.pk order_id %}'">
                <td>{{ airline.starting_airport }}</td>
                <td>{{ airline.destination_airport }}</td>
                <td>{{ airline.airlines }}</td>
                <td>{{ airline.flight }}</td>
                <td>{{ airline.aircraft_type }}</td>
                <td>{{ airline.departure_time }}</td>
                <td>{{ airline.arrival_time }}</td>
                <td>{{ airline.punctuality_rate }}</td>
                <td>{{ airline.price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}

{% endblock  %}

airlines/templates/airlines/search_result.html
{% extends 'base.html' %}

{% block content %}

<table class="table">
    <thead>
        <th>名稱</th>
        <th>類型</th>
        <th>年份</th>
    </thead>
    <tbody>
        {% for movie in movieFilter.qs %}
        <tr>
            <td>{{ movie.title }}</td>
            <td>{{ movie.get_genre_display }}</td>
            <td>{{ movie.release_year }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock  %}